# © Copyright 2024 Hewlett Packard Enterprise Development LP
---
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: ba1
spec:
  bucketAccessClassName: bac1
  credentialsSecretName: cosi-access-secret-1
  bucketClaimName: bcl1
  protocol: s3
  